apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/api-gateway:4456343fe9b852f1d87b85918d402da3d4439d7b
          imagePullPolicy: Always
