apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/api-gateway:30016a88ecbabb843a3a78c93a8c4fd82225b5ce
          imagePullPolicy: Always
