apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/api-gateway:4a80d138a4079b2841ecdeddb0ebd2a997a33648
          imagePullPolicy: Always
