apiVersion: v1
kind: Service
metadata:
  name: postgres-identity-service
spec:
  selector:
    app: identity-service-db
  ports:
    - name: postgres-identity-service
      port: 5432
      targetPort: 5432
  type: ClusterIP
