apiVersion: v1
kind: Service
metadata:
  name: postgres-recruitment-service
spec:
  selector:
    app: recruitment-service-db
  ports:
    - name: postgres-recruitment-service
      port: 5432
      targetPort: 5432
  type: ClusterIP
