apiVersion: v1
kind: Service
metadata:
  name: postgres-ai-service
spec:
  selector:
    app: ai-service-db
  ports:
    - name: postgres-ai-service
      port: 5432
      targetPort: 5432
  type: ClusterIP
