apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: identity-service-db
spec:
  serviceName: postgres-identity-service
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-db
  template:
    metadata:
      labels:
        app: identity-service-db
    spec:
      containers:
        - name: db
          image: postgres:16
          env:
          - name: POSTGRES_PASSWORD_FILE
            value: /secrets/postgres_password
          envFrom:
            - configMapRef:
                name: postgres-identity-service-config
          volumeMounts:
            - name: secret
              mountPath: "/secrets"
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: secret
          secret:
            secretName: postgres-secret
            defaultMode: 0400
            items:
            - key: POSTGRES_PASSWORD
              path: postgres_password
        - name: data
          persistentVolumeClaim:
            claimName: postgres-identity-pvc
        - name: init-scripts
          configMap:
            name: postgres-identity-init-script
            defaultMode: 0755