apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-recruitment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: custom
  resources:
    requests:
      storage: 100Mi